### ISSUE TITLE
When catkin_make, fail to include gazebo_utils.

### ISSUE THREAD

**Issue by DavidRao** [bitfsd/fssim#1]
![image](https://user-images.githubusercontent.com/48768215/112337622-0c894480-8cf9-11eb-9db6-f0dcfa67ea04.png)

![image](https://user-images.githubusercontent.com/48768215/112338999-3d1dae00-8cfa-11eb-8e96-8f40a7e038fc.png)

您好。我新建了一个工作空间，将fssim工程内的所有文件夹放入src文件夹中，执行catkin_make后出现这样的问题。文件夹gazebo_utils是在工程内的，但无法include gazebo_utils下的头文件。请问应该如何解决呢？希望能得到您的解答。

**Comment by DavidRao** [comment]
![image](https://user-images.githubusercontent.com/48768215/112347555-ee741200-8d01-11eb-9a19-93a793520ad8.png)

在引用gazebo_utils头文件的地方对应的CmakeList中加入include_directories ("/home/ubuntu/UJ/LearnROS/fssim_test_1/src/fssim_gazebo_plugins")。括号中为绝对路径

**Comment by DavidRao** [comment]
也可使用相对路径
include_directories ("../../fssim_gazebo_plugins")

**Comment by Feng1909** [comment]
请使用catkin build命令进行编译
