### ISSUE TITLE
如何显示三角剖分的三角形、参考路径及边界

### ISSUE THREAD

**Issue by KeepFighting69** [bitfsd/fssim#2]
您好，我的FSSIM能正常启动，赛车也可正常行驶，想问下如何实现在赛车跑动时能看到三角剖分的绿色三角形、边界及参考路径的显示动画？

**Comment by Feng1909** [comment]
在rviz中点击左下方的 `Add` ，点击右侧 `By topic` ，在其中点击boundary_detector发布的话题名，例如`/visualization/visual_triangles` 双击该话题名下的消息类型，就可在仿真中查看可视化

**Comment by KeepFighting69** [comment]
好的，已通过双击By topic中，/visual/pre_path下的MarkerArray显示了中间的红色参考路径，但没看到/visualization/visual_triangles这个话题

**Comment by Feng1909** [comment]
运行boundary_detector后新开一个终端，运行 `rostopic list` 命令，看看是否有 `/visualization/visual_triangles` 呢

**Comment by KeepFighting69** [comment]
运行boundary_detector.launch后，运行 rostopic list 命令有看到 /visualization/visual_triangles ，在RViz中的By topic也看到了/visualization/visual_triangles这个话题，但是双击其下的Marker，却显示报错 /0  For frame[]: Frame[] does not exist

**Comment by Feng1909** [comment]
请将https://github.com/bitfsd/fsd_algorithm/blob/master/ros/planning/boundary_detector/config/boundary_detector.yaml#L3 这一行的 `/local_map` 更改为`/map`

**Comment by KeepFighting69** [comment]
感谢，更改过后有显示剖分三角形和边界了，但是visualization话题下的Marker依然警告：best_path/0  Uninitialized quaternion, assuming identity.    MarkerArray则警告：red/0   blue/0 , 而且三角形和边界一直保持初始直道时的状态，没有跟着赛车运动而变化

**Comment by Feng1909** [comment]
请将https://github.com/bitfsd/fsd_algorithm/blob/master/ros/planning/boundary_detector/config/boundary_detector.yaml#L3 这一行的 /local_map 更改为/localmap

**Comment by KeepFighting69** [comment]
万分感谢，问题解决了

**Comment by KeepFighting69** [comment]
对了，请问FSSIM可以绘制仿真时的车速、前轮转角、跟踪误差等随时间的变化曲线图吗

**Comment by Feng1909** [comment]
可以通过PlotJuggler来订阅相关话题

**Comment by KeepFighting69** [comment]
运行 rosrun rqt_fssim_track_editor rqt_fssim_track_editor 
报错：[rospack] Error: package 'rqt_fssim_track_editor' not found
请问如何解决？

**Comment by Feng1909** [comment]
请使用`catkin build` 命令对工作空间进行编译，根据报错信息分别使用pip命令安装scipy和lxml库，即可成功运行。另外，建议新问题不要提在已经关闭的issue里，每一个问题分别对应一个独立的issue，我这几天一直没注意这个已关闭的issue有新回复

**Comment by KeepFighting69** [comment]
好的，收到，感谢感谢
